stages:
  - smoke
  - test
  - kafka

variables:
  PYTHONPATH: "${CI_PROJECT_DIR}"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  PYTEST_FLAGS: "--durations=0 --disable-pytest-warnings --color=yes --code-highlight=yes -vv --tb=short -W ignore::DeprecationWarning -W ignore::PendingDeprecationWarning -W ignore::pytest.PytestWarning --cache-clear"

.default_python_job:
  image: python:3.10
  before_script:
    - pip install -r requirements.txt || pip install pytest requests confluent_kafka
  only:
    - merge_requests
    - main

smoke_test:
  extends: .default_python_job
  stage: smoke
  script:
    - pytest tests/test_security_and_validation.py -v $PYTEST_FLAGS

main_tests:
  extends: .default_python_job
  stage: test
  script:
    - pytest tests/test_true_cases.py tests/test_false_cases.py tests/test_edge_case.py tests/full_game_flow.py -v --maxfail=1 --tb=short $PYTEST_FLAGS

kafka_tests:
  image: docker:latest
  stage: kafka
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-cli docker-compose
    - docker network create test-net || true
  script:
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml up --abort-on-container-exit
  artifacts:
    paths:
      - results/
    when: always
  rules:
    - if: '$SYSTEM_TEST =~ /.*kafka_tests.*/'
