stages:
  - smoke
  - test
  - kafka
  - security

variables:
  PYTHONPATH: "${CI_PROJECT_DIR}"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

.default_python_job:
  image: python:3.10
  before_script:
    - pip install -r requirements.txt || pip install pytest requests confluent_kafka
  only:
    - merge_requests
    - main

smoke_test:
  extends: .default_python_job
  stage: smoke
  script:
    - pytest tests/test_health_check.py -v

main_tests:
  extends: .default_python_job
  stage: test
  script:
    - pytest tests/test_true_cases.py tests/test_false_cases.py tests/test_edge_case.py -v --maxfail=1 --tb=short

kafka_tests:
  image: docker:latest
  stage: kafka
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-cli docker-compose
    - docker network create test-net || true
  script:
    - docker-compose -f docker-compose.yml up --abort-on-container-exit
  artifacts:
    paths:
      - results/
    when: always

security_check:
  extends: .default_python_job
  stage: security
  script:
    - pytest tests/test_security.py -v
