stages:
  - smoke
  - test
  - kafka

variables:
  PYTHONPATH: "${CI_PROJECT_DIR}"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  PYTEST_FLAGS: "--durations=0 --disable-pytest-warnings --color=yes --code-highlight=yes -vv --tb=short -W ignore::DeprecationWarning -W ignore::PendingDeprecationWarning -W ignore::pytest.PytestWarning --cache-clear"

.common_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"  && $SYSTEM_TEST == $CI_JOB_NAME
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SYSTEM_TEST == $CI_JOB_NAME
      when: on_success
    - when: never

.default_python_job:
  image: python:3.10
  before_script:
    - pip install -r requirements.txt || pip install pytest requests confluent_kafka
  only:
    - merge_requests
    - main

smoke_tests:
  extends: .default_python_job
  stage: smoke
  script:
    - pytest tests/test_security_and_validation.py $PYTEST_FLAGS
  rules:
    - if: $SYSTEM_TEST =~ /.*smoke_tests.*/

main_tests:
  extends: .default_python_job
  stage: test
  script:
    - pytest tests/test_true_cases.py tests/test_false_cases.py tests/test_edge_case.py tests/full_game_flow.py $PYTEST_FLAGS
  rules:
    - if: $SYSTEM_TEST =~ /.*main_tests.*/

kafka_tests:
  image: docker:latest
  stage: kafka
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-cli docker-compose
    - docker network create test-net || true
  script:
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml up --abort-on-container-exit
  artifacts:
    paths:
      - results/
    when: always
