version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=r123456clusterid
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - test-net

  test-runner:
    image: python:3.10
    depends_on:
      - kafka
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - test-net
    command: >
      sh -c "
        pip install -r requirements.txt &&
        sleep 10 &&
        python kafka_consumer.py &
        sleep 5 &&
        python kafka_producer.py
      "

networks:
  test-net:
